<template>
  <form @submit.prevent="save">
    <base-sub-nav>
      <template #default>
        <base-button
          type="submit"
          class="btn-primary"
          :disabled="!hasChanges"
          :loading="isSaving"
        >
          {{ t('common.save') }}
        </base-button>
      </template>
      <template #title>
        <h1 class="text-lg font-semibold self-center">{{ t('subtitles.title') }}</h1>
      </template>
    </base-sub-nav>

    <section class="flex flex-col gap-2 py-4 px-8">
      <base-fieldset
        :legend="t('subtitles.options.enable.legend')"
        :label="t('subtitles.options.enable.legendLabel')"
      >
        <div class="flex flex-col gap-4">
          <label class="font-semibold" for="enable-subtitles">
            {{ t('subtitles.options.enable.label') }}
          </label>
          <div class="flex items-center gap-3">
            <input
              id="enable-subtitles"
              type="checkbox"
              class="toggle toggle-primary"
              v-model="subtitleSettings.enabled"
            />
            <span class="text-sm text-base-content/70">
              {{ t('subtitles.options.enable.hint') }}
            </span>
          </div>

          <label class="font-semibold" for="auto-generated">
            {{ t('subtitles.options.autoGenerated.label') }}
          </label>
          <div class="flex items-center gap-3">
            <input
              id="auto-generated"
              type="checkbox"
              class="toggle toggle-primary"
              :disabled="!subtitleSettings.enabled"
              v-model="subtitleSettings.includeAutoGenerated"
            />
            <span class="text-sm text-base-content/70">
              {{ t('subtitles.options.autoGenerated.hint') }}
            </span>
          </div>
        </div>
      </base-fieldset>
      <div class="divider my-0"/>
      <div
        class="space-y-6"
        :class="{ 'opacity-40 pointer-events-none': !subtitleSettings.enabled }"
      >
        <base-fieldset
          :legend="t('subtitles.options.format.legend')"
          :label="t('subtitles.options.format.legendLabel')"
        >
          <label class="font-semibold" for="format-select">{{ t('subtitles.options.format.label') }}</label>
          <select
            id="format-select"
            class="select select-bordered w-full max-w-xs"
            :disabled="!subtitleSettings.enabled"
            v-model="primaryFormat"
          >
            <option
              v-for="format in subtitleFormatOptions"
              :key="format.value"
              :value="format.value"
            >
              {{ format.label }}
            </option>
          </select>
        </base-fieldset>
        <div class="divider my-2"/>
        <base-fieldset
          :legend="t('subtitles.options.languages.legend')"
          :label="t('subtitles.options.languages.legendLabel')"
        >
          <div class="flex flex-col gap-4">
            <div class="flex items-center gap-3">
              <input
                  id="all-languages"
                  type="checkbox"
                  :disabled="!subtitleSettings.enabled"
                  class="toggle toggle-primary"
                  :checked="isAllSelected"
                  @change="toggleAllLanguages"
              />
              <label class="text-sm text-base-content/70" for="all-languages">
                {{ t('subtitles.options.languages.downloadAll') }}
              </label>
            </div>

            <div class="w-full flex flex-col md:w-96">
              <label class="label" for="languageSearch">
                <span class="label-text font-semibold mb-2">
                  {{ t('subtitles.options.languages.search') }}
                </span>
              </label>
              <input
                id="languageSearch"
                type="search"
                class="input input-bordered"
                :placeholder="t('subtitles.options.languages.searchPlaceholder')"
                :disabled="!subtitleSettings.enabled"
                v-model="languageQuery"
              />
            </div>

            <div class="rounded-lg overflow-hidden">
              <template v-if="filteredSuggestedLanguageOptions.length">
                <p class="px-4 py-2 text-xs font-semibold bg-base-100 text-base-content/80">
                  {{ t('subtitles.options.languages.suggested') }}
                </p>
                <ul>
                  <li
                    v-for="option in filteredSuggestedLanguageOptions"
                    :key="option.code"
                  >
                    <label class="flex items-center gap-3 px-4 py-2 cursor-pointer has-disabled:cursor-not-allowed">
                      <input
                        type="checkbox"
                        class="checkbox checkbox-sm peer"
                        :checked="isLanguageSelected(option.code)"
                        :disabled="isAllSelected"
                        @change="toggleLanguage(option.code)"
                      />
                      <span class="flex flex-col peer-disabled:text-base-content/40">
                        <span class="font-medium">{{ option.englishName }}</span>
                        <span v-if="option.nativeName && option.nativeName !== option.englishName" class="text-xs text-base-content/60">
                          {{ option.nativeName }}
                        </span>
                      </span>
                    </label>
                  </li>
                </ul>
              </template>

              <p v-if="filteredSuggestedLanguageOptions.length && filteredLanguageOptions.length" class="px-4 py-2 text-xs font-semibold bg-base-100 text-base-content/80">
                {{ t('subtitles.options.languages.all') }}
              </p>

              <ul class="h-72 overflow-y-auto">
                <li
                  v-for="option in filteredLanguageOptions"
                  :key="option.code"
                >
                  <label class="flex items-center gap-3 px-4 py-2 cursor-pointer has-disabled:cursor-not-allowed">
                    <input
                      type="checkbox"
                      class="checkbox checkbox-sm peer"
                      :checked="isLanguageSelected(option.code)"
                      :disabled="isAllSelected"
                      @change="toggleLanguage(option.code)"
                    />
                    <span class="flex flex-col peer-disabled:text-base-content/40">
                      <span class="font-medium">{{ option.englishName }}</span>
                      <span v-if="option.nativeName && option.nativeName !== option.englishName" class="text-xs text-base-content/60">
                        {{ option.nativeName }}
                      </span>
                    </span>
                  </label>
                </li>
                <li v-if="!filteredSuggestedLanguageOptions.length && !filteredLanguageOptions.length" class="px-4 py-6 text-center text-sm text-base-content/60">
                  {{ t('subtitles.options.languages.noResult', { query: languageQuery }) }}
                </li>
              </ul>
            </div>

            <div class="flex flex-wrap gap-2 items-center text-sm">
              <span class="font-semibold">
                {{ t('subtitles.options.languages.selected') }}
              </span>
              <template v-if="isAllSelected">
                <span class="badge badge-soft badge-info">
                  {{ t('subtitles.options.languages.allSelected') }}
                </span>
              </template>
              <template v-else>
                <span
                  v-for="label in selectedLanguageBadges"
                  :key="label"
                  class="badge badge-soft"
                >
                  {{ label }}
                </span>
              </template>
            </div>

            <p class="mt-1 text-xs text-base-content/60">
              {{ t('subtitles.options.languages.searchHint') }}
            </p>
          </div>
        </base-fieldset>
      </div>
    </section>
  </form>
</template>
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import BaseButton from '../../components/base/BaseButton.vue';
import BaseFieldset from '../../components/base/BaseFieldset.vue';
import BaseSubNav from '../../components/base/BaseSubNav.vue';
import {
  detectBrowserLanguageCodes,
  languageOptionsLookup,
  languageOptions,
  type SubtitleLanguageOption,
} from '../../helpers/subtitles/languages';
import {
  DEFAULT_SUBTITLE_FORMAT_ORDER,
  sanitizeSubtitleFormats,
  sanitizeSubtitleLanguages,
} from '../../helpers/subtitles/sanitize';
import { useSettingsStore } from '../../stores/settings';
import { useToastStore } from '../../stores/toast';
import { useI18n } from 'vue-i18n';
import { SubtitleSettings } from '../../tauri/types/config.ts';

const { t } = useI18n();
const settingsStore = useSettingsStore();
const toastStore = useToastStore();

const formatLabels = new Map(
  [
    { value: 'srt', label: t('subtitles.formats.srt') },
    { value: 'vtt', label: t('subtitles.formats.vtt') },
    { value: 'ass', label: t('subtitles.formats.ass') },
    { value: 'ttml', label: t('subtitles.formats.ttml') },
    { value: 'json', label: t('subtitles.formats.json') },
  ].map(option => [option.value, option.label] as const),
);

const subtitleFormatOptions = Array.from(formatLabels.entries()).map(([value, label]) => ({
  value,
  label,
}));

const createLocalSubtitleSettings = (settings: SubtitleSettings): SubtitleSettings => ({
  enabled: settings.enabled,
  includeAutoGenerated: settings.includeAutoGenerated,
  languages: sanitizeSubtitleLanguages(settings.languages),
  formatPreference: sanitizeSubtitleFormats(settings.formatPreference),
});

const subtitleSettings = ref<SubtitleSettings>(
  createLocalSubtitleSettings(settingsStore.settings.subtitles),
);

const languageQuery = ref('');
const detectedBrowserLanguages = ref<string[]>([]);

if (typeof window !== 'undefined') {
  detectedBrowserLanguages.value = detectBrowserLanguageCodes();
}

onMounted(() => {
  detectedBrowserLanguages.value = detectBrowserLanguageCodes();
});

const isSaving = ref(false);

const hasChanges = computed(() => {
  const baseline = createLocalSubtitleSettings(settingsStore.settings.subtitles);
  return JSON.stringify(subtitleSettings.value) !== JSON.stringify(baseline);
});

const languageSelection = computed({
  get: () => subtitleSettings.value.languages,
  set: (value: string[]) => {
    subtitleSettings.value.languages = sanitizeSubtitleLanguages(value);
  },
});

const orderedFormats = computed(() =>
  sanitizeSubtitleFormats(subtitleSettings.value.formatPreference),
);

const primaryFormat = computed({
  get: () => orderedFormats.value[0] ?? DEFAULT_SUBTITLE_FORMAT_ORDER[0],
  set: (value: string) => {
    subtitleSettings.value.formatPreference = sanitizeSubtitleFormats([value]);
  },
});

const isAllSelected = computed(() => languageSelection.value.includes('all'));

const toggleAllLanguages = () => {
  if (isAllSelected.value) {
    languageSelection.value = [];
    return;
  }

  languageSelection.value = ['all'];
};

const toggleLanguage = (code: string) => {
  const next = new Set(languageSelection.value);
  if (next.has(code)) {
    next.delete(code);
  } else {
    next.add(code);
  }
  next.delete('all');
  languageSelection.value = Array.from(next);
};

const isLanguageSelected = (code: string) => languageSelection.value.includes(code);

const browserLanguageSet = computed(() => new Set(detectedBrowserLanguages.value));

const matchesQuery = (option: SubtitleLanguageOption) => {
  const query = languageQuery.value.trim().toLowerCase();
  if (!query) {
    return true;
  }

  return (
    option.englishName.toLowerCase().includes(query)
    || option.nativeName.toLowerCase().includes(query)
    || option.code.toLowerCase().includes(query)
  );
};

const filteredSuggestedLanguageOptions = computed(() =>
  languageOptions.filter(option => (
    browserLanguageSet.value.has(option.code) && (matchesQuery(option) || isLanguageSelected(option.code))),
  ),
);

const filteredLanguageOptions = computed(() =>
  languageOptions.filter(option =>
    !browserLanguageSet.value.has(option.code) && (matchesQuery(option) || isLanguageSelected(option.code)),
  ),
);

const selectedLanguageBadges = computed(() => {
  if (isAllSelected.value) {
    return [];
  }

  return languageSelection.value
    .map(code => languageOptionsLookup.get(code)?.englishName ?? code.toUpperCase())
    .filter((label, index, array) => array.indexOf(label) === index);
});

watch(
  () => settingsStore.settings.subtitles,
  (value) => {
    subtitleSettings.value = createLocalSubtitleSettings(value);
  },
  { deep: true },
);

const save = async () => {
  const normalized: SubtitleSettings = {
    enabled: subtitleSettings.value.enabled,
    includeAutoGenerated: subtitleSettings.value.includeAutoGenerated,
    languages: sanitizeSubtitleLanguages(subtitleSettings.value.languages),
    formatPreference: sanitizeSubtitleFormats(subtitleSettings.value.formatPreference),
  };

  isSaving.value = true;
  try {
    await settingsStore.patch({ subtitles: normalized });
    subtitleSettings.value = createLocalSubtitleSettings(normalized);
    toastStore.showToast(t('subtitles.toasts.saved'), { style: 'success' });
  } catch (error) {
    console.error(error);
    toastStore.showToast(t('subtitles.toasts.error', { error: String(error) }), {
      style: 'error',
    });
  } finally {
    isSaving.value = false;
  }
};
</script>
