import { AudioFormat, TranscodePolicy, VideoContainer } from './media.ts';
import { Locale } from 'vue-i18n';
import { DEFAULT_SUBTITLE_FORMAT_ORDER } from '../../helpers/subtitles/sanitize.ts';

export type Theme = 'light' | 'dark' | 'system';
export type LocaleOption = Locale | 'system';

export interface AppearanceSettings {
  theme: Theme;
  language: LocaleOption;
}

export interface AuthSettings {
  cookieFile: string | null;
  cookieBrowser: string;
}

export interface NetworkSettings {
  proxy: string | null;
  impersonate: string;
}

export interface VideoOutputSettings {
  policy: TranscodePolicy;
  container: VideoContainer;
}

export interface AudioOutputSettings {
  policy: TranscodePolicy;
  format: AudioFormat;
}

export interface InputSettings {
  autoFillClipboard: boolean;
  preferVideoInMixedLinks: boolean;
}

export enum FormatPreset {
  TitleQuality = 'titleQuality',
  TitleOnly = 'titleOnly',
  TitleQualityPlaylist = 'titleQualityPlaylist',
  Custom = 'custom',
}

export interface OutputSettings {
  video: VideoOutputSettings;
  audio: AudioOutputSettings;
  addMetadata: boolean;
  addThumbnail: boolean;
  downloadDir: string | null;
  fileNameTemplate: string;
  audioFileNameTemplate: string;
  restrictFilenames: boolean;
}

export interface PerformanceSettings {
  maxConcurrency: number;
  splitPlaylistThreshold: number;
  autoLoadSize: boolean;
}

export interface SubtitleSettings {
  enabled: boolean;
  includeAutoGenerated: boolean;
  languages: string[];
  formatPreference: string[];
}

export interface SponsorBlockSettings {
  apiUrl: string | null;
  removeParts: string[];
  markParts: string[];
}

export interface UpdateSettings {
  updateBinaries: boolean;
  updateApp: boolean;
}

export interface Settings {
  appearance: AppearanceSettings;
  auth: AuthSettings;
  network: NetworkSettings;
  input: InputSettings;
  output: OutputSettings;
  performance: PerformanceSettings;
  sponsorBlock: SponsorBlockSettings;
  subtitles: SubtitleSettings;
  update: UpdateSettings;
}

export const defaultAppearanceSettings: AppearanceSettings = {
  theme: 'system',
  language: 'system',
};

export const defaultAuthSettings: AuthSettings = {
  cookieFile: null,
  cookieBrowser: 'none',
};

export const defaultNetworkSettings: NetworkSettings = {
  proxy: null,
  impersonate: 'none',
};

export const defaultInputSettings: InputSettings = {
  autoFillClipboard: true,
  preferVideoInMixedLinks: false,
};

export const defaultOutputSettings: OutputSettings = {
  video: {
    policy: TranscodePolicy.remuxOnly,
    container: VideoContainer.mp4,
  },
  audio: {
    policy: TranscodePolicy.allowReencode,
    format: AudioFormat.mp3,
  },
  addMetadata: true,
  addThumbnail: true,
  downloadDir: null,
  fileNameTemplate: '%(title).200s-(%(height)sp%(fps).0d).%(ext)s',
  audioFileNameTemplate: '%(title).200s-(%(abr)dk).%(ext)s',
  restrictFilenames: false,
};

export const defaultPerformanceSettings: PerformanceSettings = {
  maxConcurrency: 1,
  splitPlaylistThreshold: 50,
  autoLoadSize: true,
};

export const defaultSubtitleSettings: SubtitleSettings = {
  enabled: false,
  includeAutoGenerated: false,
  languages: ['en'],
  formatPreference: [...DEFAULT_SUBTITLE_FORMAT_ORDER],
};

export const defaultSponsorBlockSettings: SponsorBlockSettings = {
  apiUrl: null,
  removeParts: [],
  markParts: [],
};

export const defaultUpdateSettings: UpdateSettings = {
  updateBinaries: true,
  updateApp: true,
};

export const defaultSettings: Settings = {
  appearance: defaultAppearanceSettings,
  auth: defaultAuthSettings,
  network: defaultNetworkSettings,
  input: defaultInputSettings,
  output: {
    ...defaultOutputSettings,
    video: { ...defaultOutputSettings.video },
    audio: { ...defaultOutputSettings.audio },
  },
  performance: defaultPerformanceSettings,
  sponsorBlock: defaultSponsorBlockSettings,
  subtitles: {
    ...defaultSubtitleSettings,
    languages: [...defaultSubtitleSettings.languages],
    formatPreference: [...defaultSubtitleSettings.formatPreference],
  },
  update: defaultUpdateSettings,
};
