import {
  AudioFormat,
  AudioPostprocessPreset,
  TranscodePolicy,
  VideoContainer,
  VideoPostprocessMode,
  VideoPostprocessPreset,
} from './media.ts';
import { Locale } from 'vue-i18n';
import { DEFAULT_SUBTITLE_FORMAT_ORDER } from '../../helpers/subtitles/sanitize.ts';
import { NotificationKind } from './app';

export type Theme = 'light' | 'dark' | 'system';
export type LocaleOption = Locale | 'system';
export type ExpandedOptions = 'none' | 'encodings' | 'tracks';

export interface AppearanceSettings {
  theme: Theme;
  language: LocaleOption;
  expandedOptions: ExpandedOptions;
}

export interface AuthSettings {
  cookieFile: string | null;
  cookieBrowser: string;
}

export interface NetworkSettings {
  enableProxy: boolean | null;
  proxy: string | null;
  impersonate: string;
  extractorArgs: string;
}

export interface VideoOutputSettings {
  policy: TranscodePolicy;
  container: VideoContainer;
  postprocessPreset: VideoPostprocessPreset;
  customPostprocessMode: VideoPostprocessMode;
  postprocessArgs: string;
}

export interface AudioOutputSettings {
  policy: TranscodePolicy;
  format: AudioFormat;
  postprocessPreset: AudioPostprocessPreset;
  postprocessArgs: string;
}

export interface InputSettings {
  autoFillClipboard: boolean;
  preferVideoInMixedLinks: boolean;
  globalShortcuts: boolean;
}

export type InputFilterSizeUnit = 'B' | 'KB' | 'MB' | 'GB' | 'TB';
export type InputFilterDateMode = 'exact' | 'before' | 'after';

export interface InputFilterSizeFilter {
  value: number | null;
  unit: InputFilterSizeUnit | null;
}

export interface InputFilterDateFilter {
  mode: InputFilterDateMode | null;
  value: string | null;
}

export interface InputFilterSettings {
  minSize: InputFilterSizeFilter;
  maxSize: InputFilterSizeFilter;
  dateFilter: InputFilterDateFilter;
  matchFilters: string | null;
  breakMatchFilters: string | null;
}

export enum FormatPreset {
  TitleQuality = 'titleQuality',
  TitleOnly = 'titleOnly',
  TitleQualityPlaylist = 'titleQualityPlaylist',
  Custom = 'custom',
}

export enum DirectoryPreset {
  None = 'none',
  Playlist = 'playlist',
  Channel = 'channel',
  ChannelPlaylist = 'channelPlaylist',
  YearMonth = 'yearMonth',
  ArtistAlbum = 'artistAlbum',
  Custom = 'custom',
}

export interface OutputSettings {
  video: VideoOutputSettings;
  audio: AudioOutputSettings;
  addMetadata: boolean;
  addThumbnail: boolean;
  saveThumbnail: boolean;
  preciseCuts: boolean;
  reversePlaylistNumbering: boolean;
  downloadDir: string | null;
  fileNameTemplate: string;
  audioFileNameTemplate: string;
  restrictFilenames: boolean;
}

export interface PerformanceSettings {
  maxConcurrency: number;
  splitPlaylistThreshold: number;
  autoLoadSize: boolean;
}

export interface SubtitleSettings {
  enabled: boolean;
  includeAutoGenerated: boolean;
  languages: string[];
  formatPreference: string[];
  embedSubtitles: boolean;
}

export interface SponsorBlockSettings {
  apiUrl: string | null;
  removeParts: string[];
  markParts: string[];
}

export interface UpdateSettings {
  updateBinaries: boolean;
  updateApp: boolean;
}

export enum CloseBehavior {
  Exit = 'exit',
  Hide = 'hide',
}

export interface SystemSettings {
  trayEnabled: boolean;
  autoStartEnabled: boolean;
  autoStartMinimised: boolean;
  closeBehavior: CloseBehavior;
}

export enum NotificationBehavior {
  Always = 'always',
  OnBackground = 'onBackground',
  Never = 'never',
}

export interface NotificationSettings {
  notificationBehavior: NotificationBehavior;
  disabledNotifications: NotificationKind[];
}

export interface Settings {
  appearance: AppearanceSettings;
  auth: AuthSettings;
  network: NetworkSettings;
  input: InputSettings;
  inputFilters: InputFilterSettings;
  output: OutputSettings;
  performance: PerformanceSettings;
  sponsorBlock: SponsorBlockSettings;
  subtitles: SubtitleSettings;
  update: UpdateSettings;
  system: SystemSettings;
  notifications: NotificationSettings;
}

export const defaultAppearanceSettings: AppearanceSettings = {
  theme: 'system',
  language: 'system',
  expandedOptions: 'none',
};

export const defaultAuthSettings: AuthSettings = {
  cookieFile: null,
  cookieBrowser: 'none',
};

export const defaultNetworkSettings: NetworkSettings = {
  enableProxy: false,
  proxy: null,
  impersonate: 'none',
  extractorArgs: '',
};

export const defaultInputSettings: InputSettings = {
  autoFillClipboard: true,
  preferVideoInMixedLinks: false,
  globalShortcuts: true,
};

export const defaultInputFilterSizeFilter: InputFilterSizeFilter = {
  value: null,
  unit: 'MB',
};

export const defaultInputFilterDateFilter: InputFilterDateFilter = {
  mode: null,
  value: null,
};

export const defaultInputFilterSettings: InputFilterSettings = {
  minSize: {
    ...defaultInputFilterSizeFilter,
  },
  maxSize: {
    ...defaultInputFilterSizeFilter,
  },
  dateFilter: {
    ...defaultInputFilterDateFilter,
  },
  matchFilters: null,
  breakMatchFilters: null,
};

export const defaultOutputSettings: OutputSettings = {
  video: {
    policy: TranscodePolicy.allowReencode,
    container: VideoContainer.mp4,
    postprocessPreset: VideoPostprocessPreset.none,
    customPostprocessMode: VideoPostprocessMode.remux,
    postprocessArgs: '',
  },
  audio: {
    policy: TranscodePolicy.allowReencode,
    format: AudioFormat.mp3,
    postprocessPreset: AudioPostprocessPreset.none,
    postprocessArgs: '',
  },
  addMetadata: true,
  addThumbnail: true,
  saveThumbnail: false,
  preciseCuts: false,
  reversePlaylistNumbering: false,
  downloadDir: null,
  fileNameTemplate: '%(title).200s-(%(height)sp%(fps).0d).%(ext)s',
  audioFileNameTemplate: '%(title).200s-(%(abr)dk).%(ext)s',
  restrictFilenames: false,
};

export const defaultPerformanceSettings: PerformanceSettings = {
  maxConcurrency: 1,
  splitPlaylistThreshold: 50,
  autoLoadSize: true,
};

export const defaultSubtitleSettings: SubtitleSettings = {
  enabled: false,
  includeAutoGenerated: false,
  languages: ['en'],
  formatPreference: [...DEFAULT_SUBTITLE_FORMAT_ORDER],
  embedSubtitles: true,
};

export const defaultSponsorBlockSettings: SponsorBlockSettings = {
  apiUrl: null,
  removeParts: [],
  markParts: [],
};

export const defaultUpdateSettings: UpdateSettings = {
  updateBinaries: true,
  updateApp: true,
};

export const defaultSystemSettings: SystemSettings = {
  trayEnabled: false,
  autoStartEnabled: false,
  autoStartMinimised: false,
  closeBehavior: CloseBehavior.Exit,
};

export const defaultNotificationSettings: NotificationSettings = {
  notificationBehavior: NotificationBehavior.Never,
  disabledNotifications: [],
};

export const defaultSettings: Settings = {
  appearance: defaultAppearanceSettings,
  auth: defaultAuthSettings,
  network: defaultNetworkSettings,
  input: defaultInputSettings,
  inputFilters: {
    ...defaultInputFilterSettings,
    minSize: { ...defaultInputFilterSettings.minSize },
    maxSize: { ...defaultInputFilterSettings.maxSize },
    dateFilter: { ...defaultInputFilterSettings.dateFilter },
  },
  output: {
    ...defaultOutputSettings,
    video: { ...defaultOutputSettings.video },
    audio: { ...defaultOutputSettings.audio },
  },
  performance: defaultPerformanceSettings,
  sponsorBlock: defaultSponsorBlockSettings,
  subtitles: {
    ...defaultSubtitleSettings,
    languages: [...defaultSubtitleSettings.languages],
    formatPreference: [...defaultSubtitleSettings.formatPreference],
  },
  update: defaultUpdateSettings,
  system: defaultSystemSettings,
  notifications: defaultNotificationSettings,
};
