export enum TrackType {
  both = 'both',
  audio = 'audio',
  video = 'video',
}

export enum TranscodePolicy {
  never = 'never',
  allowReencode = 'allowReencode',
}

export enum VideoContainer {
  mp4 = 'mp4',
  mkv = 'mkv',
}

export enum VideoPostprocessPreset {
  none = 'none',
  fps30 = 'fps30',
  mp42 = 'mp42',
  custom = 'custom',
}

export enum VideoPostprocessMode {
  remux = 'remux',
  reencode = 'reencode',
}

export enum AudioPostprocessPreset {
  none = 'none',
  custom = 'custom',
}

export enum AudioFormat {
  mp3 = 'mp3',
  m4a = 'm4a',
  opus = 'opus',
  aac = 'aac',
  ogg = 'ogg',
  flac = 'flac',
  wav = 'wav',
}

export type DownloadOptions = {
  trackType: TrackType;
  abr?: number;
  height?: number;
  fps?: number;
  audioEncoding?: string;
  videoEncoding?: string;
  audioTrack?: string;
  videoTrack?: string;
  id?: string;
  videoCodecs?: MediaCodec[];
  audioTrackIds?: string[];
  videoTrackIds?: string[];
};

export type MediaCodecInfo = {
  id: string;
  label: string;
};

export type MediaCodec = string | MediaCodecInfo;

export type DownloadOverrides = {
  output?: OutputOverrides;
  auth?: AuthOverrides;
  network?: NetworkOverrides;
  subtitles?: SubtitleOverrides;
  sponsorBlock?: SponsorBlockOverrides;
  input?: InputOverrides;
  inputFilters?: InputFilterOptions;
};

export type OutputOverrides = {
  video?: {
    container?: VideoContainer;
    policy?: TranscodePolicy;
    postprocessPreset?: VideoPostprocessPreset;
    customPostprocessMode?: VideoPostprocessMode;
    postprocessArgs?: string;
  };
  audio?: {
    format?: AudioFormat;
    policy?: TranscodePolicy;
    postprocessPreset?: AudioPostprocessPreset;
    postprocessArgs?: string;
  };
  addMetadata?: boolean;
  addThumbnail?: boolean;
  saveThumbnail?: boolean;
  preciseCuts?: boolean;
  reversePlaylistNumbering?: boolean;
  fileNameTemplate?: string;
  audioFileNameTemplate?: string;
  restrictFilenames?: boolean;
  partialDownload?: PartialDownload;
};

export type Section = {
  id: string;
  start: string;
  end: string;
};

export type Chapter = {
  title: string;
  startTime: number;
  endTime: number;
};

export type PartialDownload = {
  section?: Section;
};

export type AuthOverrides = {
  cookieFile?: string;
  cookieBrowser?: string;
  username?: string;
  password?: string;
  videoPassword?: string;
  bearerToken?: string;
  headers?: string[];
};

export type NetworkOverrides = {
  enableProxy?: boolean;
  proxy?: string;
  impersonate?: string;
  extractorArgs?: string;
};

export type SubtitleOverrides = {
  enabled?: boolean;
  includeAutoGenerated?: boolean;
  languages?: string[];
  manualLanguages?: string[];
  autoLanguages?: string[];
  formatPreference?: string[];
  embedSubtitles?: boolean;
};

export type SponsorBlockOverrides = {
  apiUrl?: string;
  removeParts?: string[];
  markParts?: string[];
};

export type InputOverrides = {
  preferVideoInMixedLinks?: boolean;
};

export enum PlaylistMode {
  singleVideo = 'singleVideo',
  playlist = 'playlist',
}

export type InputFilterOptions = {
  playlistItems?: string;
  minFilesize?: string;
  maxFilesize?: string;
  date?: string;
  datebefore?: string;
  dateafter?: string;
  matchFilters?: string;
  breakMatchFilters?: string;
  playlistMode?: PlaylistMode;
};

export type EncodingOptions = {
  audio?: string;
  video?: string;
};

export type TrackOptions = {
  audio?: string;
  video?: string;
};

export type SubtitleInventory = {
  manualLanguages: string[];
  autoLanguages: string[];
};

export interface MediaAddPayload {
  groupId: string;
  total: number;
  item: MediaItem;
}

export type MediaAddWithFormatPayload = MediaAddPayload & {
  format: DownloadOptions;
};

export interface MediaItem {
  id: string;
  url: string;
  overrides?: DownloadOverrides;
  subtitleInventory?: SubtitleInventory;
  title?: string;
  thumbnail?: string;
  description?: string;
  uploader?: string;
  uploaderId?: string;
  views?: number;
  comments?: number;
  likes?: number;
  dislikes?: number;
  duration?: number;
  rating?: number;
  extractor?: string;
  audioCodecs: MediaCodec[];
  videoCodecs?: MediaCodec[];
  audioTracks?: MediaTrack[];
  videoTracks?: MediaTrack[];
  formats: MediaFormat[];
  isLeader?: boolean;
  groupId?: string;
  filesize: number;
  chapters?: Chapter[];
  entries?: EntryItem[];
  playlistId?: string;
  playlistCount?: number;
  playlistIndex?: number;
}

export interface EntryItem {
  index: number;
  videoUrl: string;
}

export interface MediaFormat {
  id: string;
  height?: number;
  abr?: number;
  fps?: number;
  audioCodecs: MediaCodec[];
  videoCodecs: MediaCodec[];
  audioTrackIds?: string[];
  videoTrackIds?: string[];
}

export interface MediaTrack {
  id: string;
  label: string;
  language?: string;
  languagePreference?: number;
  formatNote?: string;
  format?: string;
  audioChannels?: number;
}
