name: 'Build and sign MSIX'
description: 'Builds and signs the MSIX package using Windows SDK tools'

inputs:
  layout-root:
    description: 'Root folder for the MSIX layout'
    required: false
    default: msix-layout

  app-folder-name:
    description: 'App folder name under layout root'
    required: false
    default: 'Open Video Downloader'

  manifest-path:
    description: 'Path to AppxManifest.xml (source)'
    required: false
    default: 'build\AppxManifest.xml'

  exe-path:
    description: 'Path to the built main .exe'
    required: false
    default: 'src-tauri\target\release\open-video-downloader.exe'

  license-path:
    description: 'Path to 3rd party licenses file'
    required: false
    default: 'licenses\3rdpartylicenses.txt'

  icons-glob:
    description: 'Glob for app icon assets'
    required: false
    default: 'src-tauri\icons\*.png'

  msix-path:
    description: 'Output MSIX file path'
    required: false
    default: 'OpenVideoDownloader_x64.msix'

  architecture:
    description: 'Target architecture (x64 or arm64)'
    required: false
    default: 'x64'

  pfx-b64:
    description: 'Base64-encoded PFX certificate'
    required: true

  pfx-password:
    description: 'Password for the PFX certificate'
    required: true

runs:
  using: composite
  steps:
    - name: Build and sign MSIX
      shell: pwsh
      env:
        WINDOWS_PFX_B64: ${{ inputs.pfx-b64 }}
        WINDOWS_PFX_PASSWORD: ${{ inputs.pfx-password }}
      run: |
        $ErrorActionPreference = "Stop"

        $kitsRoot = "${Env:ProgramFiles(x86)}\Windows Kits\10\bin"

        if (-not (Test-Path $kitsRoot)) {
          Write-Error "Windows 10 Kits bin folder not found at $kitsRoot"
        }

        $arch = '${{ inputs.architecture }}'

        $makeAppx = Get-ChildItem -Path $kitsRoot -Recurse -Filter "makeappx.exe" -ErrorAction SilentlyContinue |
          Where-Object { $_.FullName -match "\\$arch\\makeappx\.exe$" } |
          Select-Object -First 1

        if (-not $makeAppx) {
          Write-Error "MakeAppx.exe not found under $kitsRoot"
        }

        $signtool = Get-ChildItem -Path $kitsRoot -Recurse -Filter "signtool.exe" -ErrorAction SilentlyContinue |
          Where-Object { $_.FullName -match "\\$arch\\signtool\.exe$" } |
          Select-Object -First 1

        if (-not $signtool) {
          Write-Error "signtool.exe not found under $kitsRoot"
        }

        Write-Host "Using MakeAppx at: $($makeAppx.FullName)"
        Write-Host "Using signtool at: $($signtool.FullName)"

        $layoutRoot = '${{ inputs.layout-root }}'
        $appFolderName = '${{ inputs.app-folder-name }}'
        $manifestSrc = '${{ inputs.manifest-path }}'
        $exeSrc = '${{ inputs.exe-path }}'
        $licenseSrc = '${{ inputs.license-path }}'
        $iconsGlob = '${{ inputs.icons-glob }}'
        $arch = '${{ inputs.architecture }}'
        $msixPath = "OpenVideoDownloader_$arch.msix"

        $appFolder = Join-Path $layoutRoot $appFolderName
        $assetsFolder = Join-Path $layoutRoot "Assets"
        $licenseFolder = Join-Path $appFolder "licenses"

        New-Item -ItemType Directory -Path $appFolder, $assetsFolder, $licenseFolder -Force | Out-Null

        Copy-Item $exeSrc -Destination (Join-Path $appFolder "open-video-downloader.exe") -Force
        Copy-Item $manifestSrc -Destination (Join-Path $layoutRoot "AppxManifest.xml") -Force
        Copy-Item $iconsGlob -Destination $assetsFolder -Recurse -Force
        Copy-Item $licenseSrc -Destination (Join-Path $licenseFolder "3rdpartylicenses.txt") -Force

        $binSrc = Join-Path $appFolder "bin"
        if (-not (Test-Path $binSrc)) {
          Write-Error "Bin folder not found at '$binSrc'. Did 'npm run manifest:fetch' run?"
        }

        & "$($makeAppx.FullName)" pack /d $layoutRoot /p $msixPath

        if (-not $env:WINDOWS_PFX_B64) {
          Write-Error "WINDOWS_PFX_B64 is not set"
        }

        $certPath = Join-Path $env:RUNNER_TEMP "ovd-codesign.pfx"
        $bytes = [Convert]::FromBase64String($env:WINDOWS_PFX_B64)
        [IO.File]::WriteAllBytes($certPath, $bytes)

        $pwd = $env:WINDOWS_PFX_PASSWORD
        $timestamp = "http://timestamp.digicert.com"

        if (-not (Test-Path $msixPath)) {
          Write-Error "MSIX not found at $msixPath"
        }

        Write-Host "Signing $msixPath using dev certificate..."

        & "$($signtool.FullName)" sign `
          /fd SHA256 `
          /f "$certPath" `
          /p "$pwd" `
          /tr "$timestamp" `
          /td SHA256 `
          "$msixPath"

        Write-Host "MSIX signing complete."
