name: 'Install Tauri System Deps'
description: 'Disable docs and install all system packages needed for Tauri builds'
runs:
  using: composite
  steps:
    - name: Disable man-db/doc triggers
      shell: bash
      run: |
        sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null << 'EOF'
        path-exclude /usr/share/doc/*
        path-exclude /usr/share/man/*
        path-exclude /usr/share/info/*
        EOF
    - name: Install Ubuntu build prerequisites
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          curl \
          wget \
          file \
          libssl-dev \
          libwebkit2gtk-4.*-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev