import { mount } from '@vue/test-utils';
import { nextTick } from 'vue';
import { describe, expect, it } from 'vitest';
import TheSubtitlePreferences from '../../src/components/media-view/TheSubtitlePreferences.vue';
import { i18n } from '../../src/i18n';
import { useMediaGroupStore } from '../../src/stores/media/group';
import { useMediaOptionsStore } from '../../src/stores/media/options';
import { useSettingsStore } from '../../src/stores/settings';
import { defaultSettings } from '../../src/tauri/types/config';
import type { MediaItem } from '../../src/tauri/types/media';

function createGroupItem(id: string): MediaItem {
  return {
    id,
    url: `https://example.com/${id}`,
    audioCodecs: [],
    formats: [],
    filesize: 0,
    isLeader: true,
    subtitleInventory: {
      manualLanguages: ['en', 'de'],
      autoLanguages: ['en'],
    },
  };
}

describe('subtitle override preferences', () => {
  it('stores per-group subtitle overrides and clears them when reset', async () => {
    const groupId = 'group-subtitles';
    const settingsStore = useSettingsStore();
    settingsStore.settings.subtitles = structuredClone(defaultSettings.subtitles);

    const groupStore = useMediaGroupStore();
    groupStore.createGroup({
      id: groupId,
      url: 'https://example.com',
      total: 1,
      processed: 1,
      errored: 0,
      isCombined: false,
      audioCodecs: [],
      formats: [],
      filesize: 0,
      items: {
        leader: createGroupItem('leader'),
      },
    });

    const optionsStore = useMediaOptionsStore();
    const wrapper = mount(TheSubtitlePreferences, {
      props: {
        groupId,
      },
      global: {
        plugins: [i18n],
        stubs: {
          RouterLink: true,
        },
      },
    });

    await nextTick();
    await wrapper.get('#manual-language-de').setValue(true);
    await nextTick();

    expect(optionsStore.getOverrides(groupId)?.subtitles).toEqual({
      languages: ['en', 'de'],
      manualLanguages: ['en', 'de'],
    });

    await wrapper.get('#auto-language-en').setValue(true);
    await nextTick();

    expect(optionsStore.getOverrides(groupId)?.subtitles).toEqual({
      includeAutoGenerated: true,
      autoLanguages: ['en'],
      languages: ['en', 'de'],
      manualLanguages: ['en', 'de'],
    });

    await wrapper.get('#manual-language-en').setValue(false);
    await nextTick();
    await wrapper.get('#manual-language-de').setValue(false);
    await nextTick();
    await wrapper.get('#auto-language-en').setValue(false);
    await nextTick();

    expect(optionsStore.getOverrides(groupId)?.subtitles).toEqual({
      enabled: false,
      languages: [],
      manualLanguages: [],
    });
  });

  it('does not mark download-all as enabled when all visible boxes happen to be selected manually', async () => {
    const groupId = 'group-subtitles-manual-selection';
    const settingsStore = useSettingsStore();
    settingsStore.settings.subtitles = structuredClone(defaultSettings.subtitles);

    const groupStore = useMediaGroupStore();
    groupStore.createGroup({
      id: groupId,
      url: 'https://example.com',
      total: 1,
      processed: 1,
      errored: 0,
      isCombined: false,
      audioCodecs: [],
      formats: [],
      filesize: 0,
      items: {
        leader: {
          ...createGroupItem('leader-manual-selection'),
          subtitleInventory: {
            manualLanguages: ['en'],
            autoLanguages: ['en'],
          },
        },
      },
    });

    const wrapper = mount(TheSubtitlePreferences, {
      props: {
        groupId,
      },
      global: {
        plugins: [i18n],
        stubs: {
          RouterLink: true,
        },
      },
    });

    await nextTick();
    expect((wrapper.get('#override-all-subtitles').element as HTMLInputElement).checked).toBe(false);

    await wrapper.get('#auto-language-en').setValue(true);
    await nextTick();

    expect((wrapper.get('#override-all-subtitles').element as HTMLInputElement).checked).toBe(false);
  });
});
