import { describe, expect, it } from 'vitest';
import {
  areSubtitleSettingsEqual,
  buildSubtitleOverride,
  createSubtitleSettings,
  mergeSubtitleSettings,
} from '../../src/helpers/subtitles/settings.ts';
import { defaultSubtitleSettings } from '../../src/tauri/types/config.ts';

describe('subtitle settings helpers', () => {
  it('normalizes subtitle settings consistently', () => {
    expect(createSubtitleSettings({
      ...defaultSubtitleSettings,
      languages: [' EN ', 'en'],
      formatPreference: ['VTT'],
    })).toEqual({
      ...defaultSubtitleSettings,
      enabled: true,
      includeAutoGenerated: false,
      languages: ['en'],
      formatPreference: ['vtt', 'srt', 'ass', 'ttml', 'json3'],
    });
  });

  it('merges overrides on top of global subtitle settings', () => {
    expect(mergeSubtitleSettings(defaultSubtitleSettings, {
      languages: ['de'],
    })).toEqual({
      ...defaultSubtitleSettings,
      enabled: true,
      includeAutoGenerated: false,
      languages: ['de'],
    });
  });

  it('compares normalized subtitle settings', () => {
    expect(areSubtitleSettingsEqual(defaultSubtitleSettings, {
      ...defaultSubtitleSettings,
      languages: ['EN'],
    })).toBe(true);
  });

  it('builds only changed subtitle override fields', () => {
    expect(buildSubtitleOverride({
      ...defaultSubtitleSettings,
      languages: ['de'],
    }, defaultSubtitleSettings)).toEqual({
      languages: ['de'],
    });
  });

  it('treats an empty language selection as disabled subtitles', () => {
    expect(createSubtitleSettings({
      ...defaultSubtitleSettings,
      enabled: true,
      includeAutoGenerated: true,
      languages: [],
    })).toEqual({
      ...defaultSubtitleSettings,
      enabled: false,
      includeAutoGenerated: true,
      languages: [],
    });
  });
});
