import type { SubtitleSettings } from '../../tauri/types/config.ts';
import type { SubtitleOverrides } from '../../tauri/types/media.ts';
import {
  DEFAULT_SUBTITLE_FORMAT_ORDER,
  sanitizeSubtitleFormats,
  sanitizeSubtitleLanguages,
} from './sanitize.ts';

export interface SubtitleFormatOption {
  value: string;
  label: string;
}

function hasSelectedLanguages(languages: string[]): boolean {
  return sanitizeSubtitleLanguages(languages).length > 0;
}

export function createSubtitleSettings(settings: SubtitleSettings): SubtitleSettings {
  const languages = sanitizeSubtitleLanguages(settings.languages);
  const enabled = hasSelectedLanguages(languages);

  return {
    enabled,
    includeAutoGenerated: settings.includeAutoGenerated,
    languages,
    formatPreference: sanitizeSubtitleFormats(settings.formatPreference),
    embedSubtitles: settings.embedSubtitles,
  };
}

export function mergeSubtitleSettings(
  base: SubtitleSettings,
  override?: SubtitleOverrides,
): SubtitleSettings {
  return createSubtitleSettings({
    ...base,
    ...override,
    languages: override?.languages ?? base.languages,
    formatPreference: override?.formatPreference ?? base.formatPreference,
  });
}

export function areSubtitleSettingsEqual(a: SubtitleSettings, b: SubtitleSettings): boolean {
  return JSON.stringify(createSubtitleSettings(a)) === JSON.stringify(createSubtitleSettings(b));
}

export function buildSubtitleOverride(
  current: SubtitleSettings,
  base: SubtitleSettings,
): SubtitleOverrides | undefined {
  const normalizedCurrent = createSubtitleSettings(current);
  const normalizedBase = createSubtitleSettings(base);
  const payload: SubtitleOverrides = {};

  if (normalizedCurrent.enabled !== normalizedBase.enabled) payload.enabled = normalizedCurrent.enabled;
  if (normalizedCurrent.includeAutoGenerated !== normalizedBase.includeAutoGenerated) {
    payload.includeAutoGenerated = normalizedCurrent.includeAutoGenerated;
  }
  if (normalizedCurrent.embedSubtitles !== normalizedBase.embedSubtitles) {
    payload.embedSubtitles = normalizedCurrent.embedSubtitles;
  }
  if (JSON.stringify(normalizedCurrent.languages) !== JSON.stringify(normalizedBase.languages)) {
    payload.languages = normalizedCurrent.languages;
  }
  if (
    JSON.stringify(normalizedCurrent.formatPreference)
    !== JSON.stringify(normalizedBase.formatPreference)
  ) {
    payload.formatPreference = normalizedCurrent.formatPreference;
  }

  return Object.keys(payload).length > 0 ? payload : undefined;
}

export function buildSubtitleFormatOptions(
  t: (key: string) => string,
): SubtitleFormatOption[] {
  return [
    { value: 'srt', label: t('subtitles.formats.srt') },
    { value: 'vtt', label: t('subtitles.formats.vtt') },
    { value: 'ass', label: t('subtitles.formats.ass') },
    { value: 'ttml', label: t('subtitles.formats.ttml') },
    { value: 'json3', label: t('subtitles.formats.json3') },
  ];
}

export function getPrimarySubtitleFormat(settings: SubtitleSettings): string {
  return createSubtitleSettings(settings).formatPreference[0] ?? DEFAULT_SUBTITLE_FORMAT_ORDER[0];
}
